name: Build and Deploy Game

on:
  workflow_dispatch:
    inputs:
      deploy_to_itch:
        description: 'Deploy to itch.io'
        required: false
        default: true
        type: boolean

env:
  GODOT_VERSION: 4.4
  EXPORT_NAME: vardygr
  PROJECT_PATH: .

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot --headless --verbose --export-release "Web" build/web/index.html
      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web

  deploy-itch:
    name: Deploy to itch.io
    runs-on: ubuntu-latest
    needs: [export-web]
    if: ${{ inputs.deploy_to_itch }}
    steps:
      - name: Download Web Artifact
        uses: actions/download-artifact@v4
        with:
          name: web
          path: build/web
      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - name: Deploy to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
        run: |
          echo "${{ github.sha }}" > build/web/version.txt
          ./butler push build/web ${{ secrets.ITCH_USER }}/${{ secrets.ITCH_GAME }}:web --userversion-file build/web/version.txt